# Generated by Django 5.0.2 on 2024-02-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(default='read-only', max_length=20)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.notes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaborators',
            },
        ),
        migrations.AddField(
            model_name='notes',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', through='Notes.Collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
