# Generated by Django 5.0.2 on 2024-02-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_collaborator_notes_collaborators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='collaborator',
            old_name='user_id',
            new_name='user',
        ),
    ]
