# Generated by Django 5.0.2 on 2024-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_rename_note_id_collaborator_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.CharField(null=True),
        ),
    ]
